# Пример для проекта на Node.js
name: build
on: push
jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - name: setup node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      # Ставим зависимости
      - name: npm install
        run: make install
      # Запускаем линтер
      - name: run linter
        run: make lint
      # Запускаем тесты
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name
      # Кастомный action от Хекслета
      - uses: hexlet-components/hello-from-hexlet-action@release